### ISSUE TITLE
NO controls are added to embedded queries

### ISSUE THREAD

**Issue by gracadedues** [nothingislost/obsidian-query-control#31]
I've installed via BRAT and also tried manual. 
I've tried Minimal Theme and also Default Obsidian Theme.

However when I do a simple query:

<pre><code>```query
tag:read
```</code></pre>

All I get is the default query results. I don't see the Obsidian-Query-Control menu.

**Comment by drhos** [comment]
Same problem here in Obsidian 1.3.7...

**Comment by wwjCMP** [comment]
i have the same problem

**Comment by nothingislost** [comment]
Should be fixed in 0.5.2

**Comment by ksdavidc** [comment]
This is not fixed. I am getting message in console: 
```

loading BRAT
plugin:obsidian-query-control:6 TypeError: O is not a constructor
    at e.eval (plugin:obsidian-query-control:6:11644)
    at e.n (plugin:obsidian-query-control:6:1118)
    at e.onStart (app.js:1:1222639)
    at e.start (app.js:1:1121474)
    at e.<anonymous> (app.js:1:1122624)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at s (app.js:1:238154)
    at app.js:1:238033
    at new Promise (<anonymous>)
```

attached is a minimal example. All plugins removed, no themes, etc. Still no love..
Interestingly, my OTHER vaults work fine. JUST THIS ONE. Even if I make a copy, the copy doesn'T work either.
Tried installing, uninstalling many times. Tried reverting to older version as well.

[Personal Notes copy.zip](https://github.com/nothingislost/obsidian-query-control/files/13762687/Personal.Notes.copy.zip)

**Comment by ksdavidc** [comment]
forgot to add:SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 21.6.0: Wed Oct  4 23:55:28 PDT 2023; root:xnu-8020.240.18.704.15~1/RELEASE_X86_64 21.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 7
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 2
		1: BRAT v0.8.2
		2: Query Control v0.6.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by ksdavidc** [comment]
Lastly, sandboxed vault works ok.
